export const HOME = '/'
export const LOGOUT = '/logout'
export const BOOKS = '/books'
export const BOOK_DETAIL = '/books/:id'
export const BOOK_CREATE = '/books/create'
export const BOOK_EDIT = '/books/:id/edit'
export const BOOK_DELETE = '/books/:id/delete'
export const CATEGORIES = '/categories'
