export const HOME = '/'
export const LOGOUT = '/logout'
export const BOOKS = '/books'
export const BOOK_DETAIL = '/books/:id(\\d+)'
export const BOOK_CREATE = '/books/create'
export const CATEGORIES = '/categories'
